### ISSUE TITLE
Support for composite MVEL rules from a YAML file

### ISSUE THREAD

**Issue by kayeight** [j-easy/easy-rules#155]
Are there any plans to add support for composite rules that can be read in via yaml file? I imagine it would look something like this:

```
name: Rule name
description: Rule description
composite_type: UnitRuleGroup
priority: 100
subrules:
  - name: Subrule 1
    description: Description
    priority: 100
    condition: "true"
    actions:
      - "someAction();"
  - name: Subrule 2
    description: Description
    priority: 100
    condition: "true"
    actions:
      - "someAction();"
  - name: Subrule 3
    description: Description
    priority: 100
    condition: "true"
    actions:
      - "someAction();"
```
