### ISSUE TITLE
is there a way to add static method to YML file Condition

### ISSUE THREAD

**Issue by ruchichhabra009** [j-easy/easy-rules#162]
Hi @benas 

Is there a way to add have something like this condition. 
Hi @benas 

I have modified the YML and it worked this way for me. But condition is not working. Could you please suggest.

```yml
validationName: "duration-validation.yml"
field: "duration"
ruleName: "duration-NullCheck"
description: "duration should not be empty"
optional: true
reason: "Missing duration"
priority: 1
condition: "RuleUtil.durationNullCheck(duration)"
actions:
  - "System.out.println(\"duration value is not available\")"
```
