### ISSUE TITLE
dose easy-rules support Enum types?

### ISSUE THREAD

**Issue by wenweihu86** [j-easy/easy-rules#258]

**Comment by benas** [comment]
Can you elaborate with an example please?

**Comment by wenweihu86** [comment]
the facts has enum type, and I want to use the enum within the rule, so that it can improve rules code readability.

**Comment by benas** [comment]
ok thanks. That is a feature of the expression language you use and not Easy Rules itself. I believe Mvel and SpEL both provide support for enums in expressions. Here is a quick example with MVEL:

Given the following `gender-rule.yml`:

```yaml
name: male rule
condition: "person.gender == Gender.MALE"
actions:
  - "System.out.println(person.name + \" is male\");"
---
name: female rule
condition: "person.gender == Gender.FEMALE"
actions:
  - "System.out.println(person.name + \" is female\");"
```

The following example:

```java
import java.io.File;
import java.io.FileReader;

import org.jeasy.rules.api.Facts;
import org.jeasy.rules.api.Rules;
import org.jeasy.rules.api.RulesEngine;
import org.jeasy.rules.core.DefaultRulesEngine;
import org.jeasy.rules.support.YamlRuleDefinitionReader;
import org.junit.Test;
import org.mvel2.ParserContext;

public class GenderRuleTest {

	@Test
	public void testGenderRules() throws Exception {
		MVELRuleFactory factory = new MVELRuleFactory(new YamlRuleDefinitionReader());
		File rulesDescriptor = new File("gender-rule.yml");

		ParserContext parserContext = new ParserContext();
		parserContext.addImport(Gender.class);
		Rules rules = factory.createRules(new FileReader(rulesDescriptor), parserContext);
		Facts facts = new Facts();
		facts.put("person", new Person("foo", Gender.MALE));

		RulesEngine rulesEngine = new DefaultRulesEngine();
		rulesEngine.fire(rules, facts);
		facts.put("person", new Person("bar", Gender.FEMALE));
		rulesEngine.fire(rules, facts);
	}
	
	public static class Person {
		private String name;
		private Gender gender;
		private boolean male;

		public Person(String name, Gender gender) {
			this.name = name;
			this.gender = gender;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public Gender getGender() {
			return gender;
		}

		public void setGender(Gender gender) {
			this.gender = gender;
		}

		public boolean isMale() {
			return male;
		}

		public void setMale(boolean male) {
			this.male = male;
		}
	}
	
	public enum Gender {
		MALE, FEMALE
	}
}
```

prints:

```
foo is male
bar is female
```

Hope this helps.
