### ISSUE TITLE
Failed to resolve multiple rules

### ISSUE THREAD

**Issue by henryyan** [j-easy/easy-rules#285]
### weather-rule-spel.yml

```yaml
name: Movie id rule
compositeRuleType: UnitRuleGroup
priority: 1
composingRules:
  - name: Time is evening
    description: If it's later than 7pm
    priority: 1
    condition: "#{ ['day'].hour > 19 }"
    actions:
      - "#{ ['person'].shouldProvideId(true) }"
  - name: Movie is rated R
    description: If the movie is rated R
    priority: 1
    condition: "#{ ['movie'].rating == 'R' }"
    actions:
      - "#{ ['person'].shouldProvideId(true) }"
---
name: weather rule
description: when it rains, then take an umbrella
priority: 1
condition: "#{ ['rain'] == true }"
actions:
  - "#{ T(System).out.println(\"It rains, take an umbrella!\") }"
```

### Java codes

```java
import java.io.FileReader;
import java.util.Map;

import org.jeasy.rules.api.Facts;
import org.jeasy.rules.api.Rule;
import org.jeasy.rules.api.Rules;
import org.jeasy.rules.api.RulesEngine;
import org.jeasy.rules.core.DefaultRulesEngine;
import org.jeasy.rules.spel.SpELRuleFactory;
import org.jeasy.rules.support.reader.YamlRuleDefinitionReader;

/**
 * @author henry.yhl
 * @since 2020/6/3
 */
public class YamlSpElLauncher {

    public static void main(String[] args) {
        SpELRuleFactory ruleFactory = new SpELRuleFactory(new YamlRuleDefinitionReader());
        try {
            Rules weatherRule = ruleFactory.createRules(new FileReader("/Users/henryyan/.../weather-rule-spel.yml"));

            // define facts
            Facts facts = new Facts();
            facts.put("rain", true);

            facts.put("day", new DayDto(20));
            facts.put("movie", new Movie("R"));
            facts.put("person", new Person());

            Rules rules = new Rules();
            rules.register(weatherRule);

            // fire rules on known facts
            RulesEngine rulesEngine = new DefaultRulesEngine();
            Map<Rule, Boolean> check = rulesEngine.check(rules, facts);
            System.out.println(check);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static class DayDto {
        private int hour;

        public DayDto(int hour) {
            this.hour = hour;
        }

        public int getHour() {
            return hour;
        }

        public void setHour(int hour) {
            this.hour = hour;
        }
    }

    static class Movie {
        private String rating;

        public Movie(String rating) {
            this.rating = rating;
        }

        public String getRating() {
            return rating;
        }

        public void setRating(String rating) {
            this.rating = rating;
        }
    }

    static class Person {
        public void shouldProvideId(boolean provide) {
            System.out.println("support is " + provide);
        }
    }
}
```

### get exception

```
java.lang.IllegalArgumentException: Rule 'org.jeasy.rules.api.Rules' is not annotated with 'org.jeasy.rules.annotation.Rule'
	at org.jeasy.rules.core.RuleDefinitionValidator.checkRuleClass(RuleDefinitionValidator.java:57)
	at org.jeasy.rules.core.RuleDefinitionValidator.validateRuleDefinition(RuleDefinitionValidator.java:49)
	at org.jeasy.rules.core.RuleProxy.asRule(RuleProxy.java:81)
	at org.jeasy.rules.api.Rules.register(Rules.java:80)
	at com.alibaba.cse.YamlSpElLauncher.main(YamlSpElLauncher.java:37)
```

### Debug info

![image](https://user-images.githubusercontent.com/1219399/83643123-3d6d8100-a5e2-11ea-9471-78e579b5fc87.png)
